# ==========================================
# Fichier de Configuration SonarCloud
# ==========================================

# Identifiants du projet sur SonarCloud (https://sonarcloud.io)
sonar.organization=stevetetchoup26
sonar.projectKey=SteveTetchoup26_santeConnect
sonar.projectName=SanteConnect
sonar.projectVersion=1.0.0

# Chemins vers les sources et les tests
sonar.sources=src
sonar.tests=tests

# Encodage des fichiers sources
sonar.sourceEncoding=UTF-8

# Spécification TypeScript
sonar.typescript.tsconfigPath=tsconfig.json

# Chemin vers le rapport de couverture de tests LCOV généré par Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclusions de l'analyse (fichiers de configuration, dépendances et builds)
sonar.exclusions=node_modules/**, dist/**, coverage/**, tests/**, jest.config.ts, tsconfig.json, Dockerfile, docker-compose.yml, .github/**

# Porte de qualité (Quality Gate) : 
# SonarQube renverra une erreur si :
# 1. La couverture de test globale est inférieure à 80%
# 2. Des failles de sécurité critiques ou bloquantes sont détectées
# Ce paramètre force l'analyse à attendre le résultat de la Quality Gate
sonar.qualitygate.wait=true
